databases:
  - name: divisorsilabasdb
    plan: free
    databaseName: divisorsilabas
    user: divisorsilabas

services:
  - type: web
    plan: free
    name: divisorsilabas
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn divisorsilabas_project.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: divisorsilabasdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4